name: freezed_learn
description: A simple command-line application.
version: 1.0.0
# homepage: https://www.example.com

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  meta: ^1.4.0
  freezed_annotation: ^0.12.0
  json_annotation:

dev_dependencies:
  build_runner: ^2.0.4
  freezed:
  json_serializable:
